import { ApiState } from "@/scenes/state/types";

// Mock user data
export const mockUserData: ApiState = {
  data: [
    {
      playlist_id: 1,
      user_id: 1,
      spotify_playlist_id: "spotify_playlist_1",
      playlist_name: "Chill Vibes",
      latitude_created: 40.7128,
      longitude_created: -74.006,
      timestamp_created: "2023-01-23T18:25:43.511Z",
      seed_tracks: ["track1", "track2"],
      target_acousticness: 0.6,
      target_danceability: 0.7,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 2,
      user_id: 1,
      spotify_playlist_id: "spotify_playlist_2",
      playlist_name: "Workout Beats",
      latitude_created: 34.0522,
      longitude_created: -118.2437,
      timestamp_created: "2022-12-23T13:25:43.511Z",
      seed_tracks: ["track3", "track4"],
      target_acousticness: 0.3,
      target_danceability: 0.8,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 3,
      user_id: 2,
      spotify_playlist_id: "spotify_playlist_3",
      playlist_name: "Study Music",
      latitude_created: 51.5074,
      longitude_created: -0.1278,
      timestamp_created: "2022-08-23T12:25:43.511Z",
      seed_tracks: ["track5", "track6"],
      target_acousticness: 0.5,
      target_danceability: 0.4,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 4,
      user_id: 2,
      spotify_playlist_id: "spotify_playlist_4",
      playlist_name: "Road Trip Tunes",
      latitude_created: 37.7749,
      longitude_created: -122.4194,
      timestamp_created: "2022-08-23T18:25:43.511Z",
      seed_tracks: ["track7", "track8"],
      target_acousticness: 0.4,
      target_danceability: 0.6,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 5,
      user_id: 3,
      spotify_playlist_id: "spotify_playlist_5",
      playlist_name: "Study Music",
      latitude_created: 51.5074,
      longitude_created: -0.1278,
      timestamp_created: "2022-09-23T20:25:43.511Z",
      seed_tracks: ["track5", "track6"],
      target_acousticness: 0.5,
      target_danceability: 0.4,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 6,
      user_id: 3,
      spotify_playlist_id: "spotify_playlist_6",
      playlist_name: "Road Trip Tunes",
      latitude_created: 37.7749,
      longitude_created: -122.4194,
      timestamp_created: "2022-10-23T21:25:43.511Z",
      seed_tracks: ["track7", "track8"],
      target_acousticness: 0.4,
      target_danceability: 0.6,
      target_energy: 0.5,
      target_liveness: 0.5,
      target_loudness: 0.5,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 7,
      user_id: 4,
      spotify_playlist_id: "spotify_playlist_7",
      playlist_name: "Relaxing Evening",
      latitude_created: 35.6895,
      longitude_created: 139.6917,
      timestamp_created: "2012-04-24T16:15:43.511Z",
      seed_tracks: ["track9", "track10"],
      target_acousticness: 0.7,
      target_danceability: 0.3,
      target_energy: 0.4,
      target_liveness: 0.2,
      target_loudness: 0.6,
      target_speechiness: 0.5,
      target_tempo: 0.4,
      target_valence: 0.6,
    },
    {
      playlist_id: 8,
      user_id: 5,
      spotify_playlist_id: "spotify_playlist_8",
      playlist_name: "Morning Boost",
      latitude_created: 48.8566,
      longitude_created: 2.3522,
      timestamp_created: "2023-04-25T08:25:43.511Z",
      seed_tracks: ["track11", "track12"],
      target_acousticness: 0.3,
      target_danceability: 0.7,
      target_energy: 0.8,
      target_liveness: 0.5,
      target_loudness: 0.7,
      target_speechiness: 0.5,
      target_tempo: 0.6,
      target_valence: 0.7,
    },
    {
      playlist_id: 9,
      user_id: 5,
      spotify_playlist_id: "spotify_playlist_9",
      playlist_name: "Night Drive",
      latitude_created: 40.4168,
      longitude_created: -3.7038,
      timestamp_created: "2023-02-25T19:45:43.511Z",
      seed_tracks: ["track13", "track14"],
      target_acousticness: 0.4,
      target_danceability: 0.6,
      target_energy: 0.7,
      target_liveness: 0.5,
      target_loudness: 0.6,
      target_speechiness: 0.5,
      target_tempo: 0.5,
      target_valence: 0.6,
    },
    {
      playlist_id: 10,
      user_id: 6,
      spotify_playlist_id: "spotify_playlist_10",
      playlist_name: "Coffee Shop Vibes",
      latitude_created: 52.3676,
      longitude_created: 4.9041,
      timestamp_created: "2022-11-26T09:35:43.511Z",
      seed_tracks: ["track15", "track16"],
      target_acousticness: 0.5,
      target_danceability: 0.8,
      target_energy: 0.5,
      target_liveness: 0.2,
      target_loudness: 0.5,
      target_speechiness: 0.4,
      target_tempo: 0.5,
      target_valence: 0.5,
    },
    {
      playlist_id: 11,
      user_id: 6,
      spotify_playlist_id: "spotify_playlist_11",
      playlist_name: "Gym Pump",
      latitude_created: 52.52,
      longitude_created: 13.405,
      timestamp_created: "2022-08-27T10:15:43.511Z",
      seed_tracks: ["track17", "track18"],
      target_acousticness: 0.55,
      target_danceability: 0.9,
      target_energy: 0.9,
      target_liveness: 0.5,
      target_loudness: 0.7,
      target_speechiness: 0.5,
      target_tempo: 0.8,
      target_valence: 0.7,
    },
    {
      playlist_id: 12,
      user_id: 7,
      spotify_playlist_id: "spotify_playlist_12",
      playlist_name: "Rainy Day",
      latitude_created: 55.7558,
      longitude_created: 37.6176,
      timestamp_created: "2023-03-28T15:05:43.511Z",
      seed_tracks: ["track19", "track20"],
      target_acousticness: 0.8,
      target_danceability: 0.4,
      target_energy: 0.4,
      target_liveness: 0.2,
      target_loudness: 0.5,
      target_speechiness: 0.4,
      target_tempo: 0.5,
      target_valence: 0.4,
    },
    {
      playlist_id: 13,
      user_id: 7,
      spotify_playlist_id: "spotify_playlist_13",
      playlist_name: "Beach Day",
      latitude_created: 25.7617,
      longitude_created: -80.1918,
      timestamp_created: "2023-05-29T11:05:43.511Z",
      seed_tracks: ["track21", "track22"],
      target_acousticness: 0.4,
      target_danceability: 0.7,
      target_energy: 0.6,
      target_liveness: 0.5,
      target_loudness: 0.6,
      target_speechiness: 0.5,
      target_tempo: 0.6,
      target_valence: 0.7,
    },
    {
      playlist_id: 14,
      user_id: 8,
      spotify_playlist_id: "spotify_playlist_14",
      playlist_name: "Sunday Morning",
      latitude_created: 48.1351,
      longitude_created: 11.582,
      timestamp_created: "2023-06-30T08:25:43.511Z",
      seed_tracks: ["track23", "track24"],
      target_acousticness: 0.7,
      target_danceability: 0.5,
      target_energy: 0.5,
      target_liveness: 0.3,
      target_loudness: 0.5,
      target_speechiness: 0.4,
      target_tempo: 0.5,
      target_valence: 0.6,
    },
  ],
  feedbackData: [
    {
      feedback_id: 1,
      user_id: 1,
      feedback_text: "Great app, really enjoy using it!",
      fb_timestamp: "2022-01-01T12:00:00Z",
    },
    {
      feedback_id: 2,
      user_id: 1,
      feedback_text: "Could use some more features.",
      fb_timestamp: "2022-01-02T12:00:00Z",
    },
    {
      feedback_id: 3,
      user_id: 2,
      feedback_text: "Easy to use and very helpful.",
      fb_timestamp: "2022-01-03T12:00:00Z",
    },
    {
      feedback_id: 4,
      user_id: 3,
      feedback_text: "Had some issues with the interface.",
      fb_timestamp: "2022-01-04T12:00:00Z",
    },
    {
      feedback_id: 5,
      user_id: 3,
      feedback_text: "Customer support was very helpful.",
      fb_timestamp: "2022-01-05T12:00:00Z",
    },
    {
      feedback_id: 6,
      user_id: 4,
      feedback_text: "The recent update improved performance a lot!",
      fb_timestamp: "2022-01-06T12:00:00Z",
    },
    {
      feedback_id: 7,
      user_id: 5,
      feedback_text: "I wish there was a dark mode option.",
      fb_timestamp: "2022-01-07T12:00:00Z",
    },
    {
      feedback_id: 8,
      user_id: 6,
      feedback_text:
        "Took me a while to get used to it, but now I love it. Took me a while to get used to it, but now I love it. Took me a while to get used to it, but now I love it.",
      fb_timestamp: "2022-01-08T12:00:00Z",
    },
    {
      feedback_id: 9,
      user_id: 6,
      feedback_text: "Would love more customization features.",
      fb_timestamp: "2022-01-09T12:00:00Z",
    },
    {
      feedback_id: 10,
      user_id: 7,
      feedback_text: "Great for daily tasks and organization.",
      fb_timestamp: "2022-01-10T12:00:00Z",
    },
    {
      feedback_id: 11,
      user_id: 8,
      feedback_text: "Occasionally crashes on my device.",
      fb_timestamp: "2022-01-11T12:00:00Z",
    },
    {
      feedback_id: 12,
      user_id: 9,
      feedback_text: "Impressive design and usability.",
      fb_timestamp: "2022-01-12T12:00:00Z",
    },
    {
      feedback_id: 13,
      user_id: 10,
      feedback_text: "Integration with other apps would be perfect.",
      fb_timestamp: "2022-01-13T12:00:00Z",
    },
  ],
  loading: false,
};
